In [10]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
dataset = pd.read_csv(r'../data/NepalLatestAQI.csv')
dataset.head()

,date,station,latitude,longitude,aqi,pm2_5,pm10,no2,so2,o3,temperature_C,relative_humidity_%,notes
0,2024-01-01,Kathmandu,27.7172,85.3240,162,75.9,161.5,18.5,8.0,16.2,20.9,65.2,NaN
1,2024-01-01,Lalitpur,27.6648,85.3188,157,66.9,105.9,18.2,4.2,34.1,28.8,76.2,NaN
2,2024-01-01,Bhaktapur,27.6714,85.4270,166,84.8,182.9,16.4,7.1,26.7,20.3,60.9,NaN
3,2024-01-01,Pokhara,28.2096,83.9856,79,25.5,47.8,2.0,1.0,31.7,23.0,47.9,NaN
4,2024-01-01,Biratnagar,26.4525,87.2718,146,53.8,86.3,17.2,1.9,34.5,23.9,54.1,NaN

In [3]:
dataset.isnull().sum()

date                      0
station                   0
latitude                  0
longitude                 0
aqi                       0
pm2_5                     0
pm10                      0
no2                       0
so2                       0
o3                        0
temperature_C             0
relative_humidity_%       0
notes                  9761
dtype: int64

In [4]:
dataset = dataset.drop(columns='notes')

In [5]:
dataset = dataset.rename(columns=lambda c: c.strip())

In [6]:
dataset = dataset.sort_values('date').drop_duplicates(subset=['station', 'date'], keep='last')

In [13]:
dataset['date'] = pd.to_datetime(dataset['date'])
dataset['month'] = dataset['date'].dt.month
dataset['day'] = dataset['date'].dt.day
dataset['dayofweek'] = dataset['date'].dt.dayofweek
dataset['is_weekend'] = dataset['dayofweek'].isin([5,6]).astype(int)

❗ Why do we encode cyclical features?

Months and weekdays are cyclical:

After December (12) comes January (1)

After Sunday (6) comes Monday (0)

If you use raw numbers:

The model thinks January (1) is far from December (12)
But they are next to each other.

In [16]:
dataset['month_sin'] = np.sin(2 * np.pi * dataset['month']/12)
dataset['month_cos'] = np.cos(2 * np.pi * dataset['month']/12)
dataset['dow_sin'] = np.sin(2 * np.pi * dataset['dayofweek']/7)
dataset['dow_cos'] = np.cos(2 * np.pi * dataset['dayofweek']/7)

,date,station,latitude,longitude,aqi,pm2_5,pm10,no2,so2,o3,temperature_C,relative_humidity_%,month,day,dayofweek,is_weekend,month_sin,month_cos,dow_sin,dow_cos
9826,2025-10-17,Lalitpur,27.6648,85.3188,136,49.8,91.9,25.7,4.4,26.1,13.2,49.2,10,17,4,0,-0.866025,0.5,-0.433884,-0.900969
9825,2025-10-17,Kathmandu,27.7172,85.3240,121,43.5,84.5,33.8,4.6,32.6,14.9,56.1,10,17,4,0,-0.866025,0.5,-0.433884,-0.900969
9838,2025-10-17,Jumla,29.2741,82.1855,64,18.1,26.6,14.6,1.2,33.9,17.1,68.3,10,17,4,0,-0.866025,0.5,-0.433884,-0.900969
9831,2025-10-17,Bharatpur,27.6838,84.4328,84,27.8,39.0,5.6,4.5,9.9,9.6,52.2,10,17,4,0,-0.866025,0.5,-0.433884,-0.900969
9839,2025-10-17,Illam,26.8901,87.9204,98,34.4,82.1,2.0,7.9,56.1,16.8,43.9,10,17,4,0,-0.866025,0.5,-0.433884,-0.900969