In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
dataset = pd.read_csv(r'../data/NepalLatestAQI.csv')
dataset.head()

,date,station,latitude,longitude,aqi,pm2_5,pm10,no2,so2,o3,temperature_C,relative_humidity_%,notes
0,2024-01-01,Kathmandu,27.7172,85.3240,162,75.9,161.5,18.5,8.0,16.2,20.9,65.2,NaN
1,2024-01-01,Lalitpur,27.6648,85.3188,157,66.9,105.9,18.2,4.2,34.1,28.8,76.2,NaN
2,2024-01-01,Bhaktapur,27.6714,85.4270,166,84.8,182.9,16.4,7.1,26.7,20.3,60.9,NaN
3,2024-01-01,Pokhara,28.2096,83.9856,79,25.5,47.8,2.0,1.0,31.7,23.0,47.9,NaN
4,2024-01-01,Biratnagar,26.4525,87.2718,146,53.8,86.3,17.2,1.9,34.5,23.9,54.1,NaN

In [4]:
dataset.isnull().sum()

date                      0
station                   0
latitude                  0
longitude                 0
aqi                       0
pm2_5                     0
pm10                      0
no2                       0
so2                       0
o3                        0
temperature_C             0
relative_humidity_%       0
notes                  9761
dtype: int64

In [5]:
dataset = dataset.drop(columns='notes')

In [10]:
dataset.shape

(9796, 12)

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9840 entries, 0 to 9839
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 9840 non-null   object
 1   station              9840 non-null   object
 2   latitude             9840 non-null   float64
 3   longitude            9840 non-null   float64
 4   aqi                  9840 non-null   int64
 5   pm2_5                9840 non-null   float64
 6   pm10                 9840 non-null   float64
 7   no2                  9840 non-null   float64
 8   so2                  9840 non-null   float64
 9   o3                   9840 non-null   float64
 10  temperature_C        9840 non-null   float64
 11  relative_humidity_%  9840 non-null   float64
dtypes: float64(9), int64(1), object(2)
memory usage: 922.6+ KB

In [11]:
dataset.describe()

,latitude,longitude,aqi,pm2_5,pm10,no2,so2,o3,temperature_C,relative_humidity_%
count,9796.000000,9796.000000,9796.000000,9796.000000,9796.000000,9796.000000,9796.000000,9796.00000,9796.000000,9796.000000
mean,27.597600,84.708188,96.704369,34.618834,69.378716,14.144345,3.745631,40.98381,21.260014,55.448275
std,0.742909,2.023898,37.507395,18.921170,40.561707,7.929011,1.886145,14.79263,7.788292,14.829080
min,26.452500,80.591200,4.000000,1.000000,1.000000,2.000000,1.000000,3.80000,1.100000,10.000000
25%,26.890100,83.450000,70.000000,21.200000,40.800000,8.000000,2.300000,29.90000,14.500000,45.000000
50%,27.671400,85.030600,93.000000,31.900000,63.000000,13.400000,3.600000,38.60000,21.900000,54.500000
75%,28.058200,85.924600,124.000000,44.900000,90.300000,19.700000,5.000000,50.50000,27.800000,65.300000
max,29.274100,87.920400,236.000000,185.500000,450.500000,43.400000,11.000000,98.90000,40.000000,100.000000

In [9]:
dataset = dataset[dataset['aqi']<=265]

In [12]:
dataset.to_csv('../data/CleanData.csv', index=False)